#!/usr/bin/env python3
# Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate scalar register declarations/accessors for the persistent GDN CTA.

The state is deliberately emitted as individually named scalar variables.  A
runtime-indexed C array would be lowered to local memory, which would silently
turn the intended RF-resident state into global-memory traffic.
"""

from pathlib import Path

LAYERS = 24
VALUES_PER_LAYER_PER_THREAD = 6
VALUES = LAYERS * VALUES_PER_LAYER_PER_THREAD


def name(index: int) -> str:
    return f"r{index:03d}"


GENERATED_LICENSE = [
    "/*",
    " * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.",
    " *",
    ' * Licensed under the Apache License, Version 2.0 (the "License");',
    " * you may not use this file except in compliance with the License.",
    " * You may obtain a copy of the License at",
    " *",
    " *     http://www.apache.org/licenses/LICENSE-2.0",
    " *",
    " * Unless required by applicable law or agreed to in writing, software",
    ' * distributed under the License is distributed on an "AS IS" BASIS,',
    " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
    " * See the License for the specific language governing permissions and",
    " * limitations under the License.",
    " */",
    "",
]


lines = [
    *GENERATED_LICENSE,
    "// Generated by generate_register_state.py. Do not edit by hand.",
    "#pragma once",
    "",
    "// clang-format off",
    "#define GDN_DECLARE_RF_STATE() \\",
]
for index in range(VALUES):
    suffix = " \\" if index + 1 < VALUES else ""
    lines.append(f"  float {name(index)} = 0.0f;{suffix}")

lines.extend(
    [
        "",
        "#define GDN_LOAD_RF_LAYER_CASE(LAYER) \\",
        "  case LAYER: { \\",
    ]
)
for slot in range(VALUES_PER_LAYER_PER_THREAD):
    index = slot
    lines.append(
        f"    {name(index)} = init_state[rf_global_offset((LAYER), tid, {slot}, row_base)]; \\"
    )
lines.extend(["    break; \\", "  }", ""])

# The load/store/update cases must refer to a different set of six scalar
# variables for every compile-time layer. Emit complete switches rather than
# indexing an array with the runtime layer id.
for macro, expression in (
    ("GDN_LOAD_RF_SWITCH", "init_state[rf_global_offset(L, tid, S, row_base)]"),
    ("GDN_ADD_RF_SWITCH", "REG + delta"),
    ("GDN_STORE_RF_SWITCH", "final_state[rf_global_offset(L, tid, S, row_base)] = REG"),
):
    lines.append(f"#define {macro}(RUNTIME_LAYER, BODY_DEFAULT) \\")
    lines.append("  switch (RUNTIME_LAYER) { \\")
    for layer in range(LAYERS):
        lines.append(f"    case {layer}: {{ \\")
        for slot in range(VALUES_PER_LAYER_PER_THREAD):
            reg = name(layer * VALUES_PER_LAYER_PER_THREAD + slot)
            if macro == "GDN_LOAD_RF_SWITCH":
                statement = (
                    f"{reg} = rf_row_valid(tid, {slot}, row_base) "
                    f"? init_state[rf_global_offset({layer}, tid, {slot}, row_base)] "
                    ": 0.0f;"
                )
            elif macro == "GDN_ADD_RF_SWITCH":
                statement = f"{reg} += delta;"
            else:
                statement = (
                    f"if (rf_row_valid(tid, {slot}, row_base)) "
                    "{ final_state[rf_global_offset("
                    f"{layer}, tid, {slot}, row_base)] = {reg}; }}"
                )
            lines.append(f"      {statement} \\")
        lines.extend(["      break; \\", "    } \\"])
    lines.extend(["    default: { BODY_DEFAULT; break; } \\", "  }", ""])

for macro, destination in (
    ("GDN_STAGE_RF_SWITCH", "rf_stage[tid + S * kThreads] = REG"),
    ("GDN_UNSTAGE_RF_SWITCH", "REG = rf_stage[tid + S * kThreads]"),
):
    lines.append(f"#define {macro}(RUNTIME_LAYER, BODY_DEFAULT) \\")
    lines.append("  switch (RUNTIME_LAYER) { \\")
    for layer in range(LAYERS):
        lines.append(f"    case {layer}: {{ \\")
        for slot in range(VALUES_PER_LAYER_PER_THREAD):
            reg = name(layer * VALUES_PER_LAYER_PER_THREAD + slot)
            statement = destination.replace("REG", reg).replace("S", str(slot))
            lines.append(f"      {statement}; \\")
        lines.extend(["      break; \\", "    } \\"])
    lines.extend(["    default: { BODY_DEFAULT; break; } \\", "  }", ""])

lines.append("// clang-format on")

Path(__file__).with_name("register_state_generated.cuh").write_text("\n".join(lines) + "\n")
