/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_register_state.py. Do not edit by hand.
#pragma once

// clang-format off
#define GDN_DECLARE_RF_STATE() \
  float r000 = 0.0f; \
  float r001 = 0.0f; \
  float r002 = 0.0f; \
  float r003 = 0.0f; \
  float r004 = 0.0f; \
  float r005 = 0.0f; \
  float r006 = 0.0f; \
  float r007 = 0.0f; \
  float r008 = 0.0f; \
  float r009 = 0.0f; \
  float r010 = 0.0f; \
  float r011 = 0.0f; \
  float r012 = 0.0f; \
  float r013 = 0.0f; \
  float r014 = 0.0f; \
  float r015 = 0.0f; \
  float r016 = 0.0f; \
  float r017 = 0.0f; \
  float r018 = 0.0f; \
  float r019 = 0.0f; \
  float r020 = 0.0f; \
  float r021 = 0.0f; \
  float r022 = 0.0f; \
  float r023 = 0.0f; \
  float r024 = 0.0f; \
  float r025 = 0.0f; \
  float r026 = 0.0f; \
  float r027 = 0.0f; \
  float r028 = 0.0f; \
  float r029 = 0.0f; \
  float r030 = 0.0f; \
  float r031 = 0.0f; \
  float r032 = 0.0f; \
  float r033 = 0.0f; \
  float r034 = 0.0f; \
  float r035 = 0.0f; \
  float r036 = 0.0f; \
  float r037 = 0.0f; \
  float r038 = 0.0f; \
  float r039 = 0.0f; \
  float r040 = 0.0f; \
  float r041 = 0.0f; \
  float r042 = 0.0f; \
  float r043 = 0.0f; \
  float r044 = 0.0f; \
  float r045 = 0.0f; \
  float r046 = 0.0f; \
  float r047 = 0.0f; \
  float r048 = 0.0f; \
  float r049 = 0.0f; \
  float r050 = 0.0f; \
  float r051 = 0.0f; \
  float r052 = 0.0f; \
  float r053 = 0.0f; \
  float r054 = 0.0f; \
  float r055 = 0.0f; \
  float r056 = 0.0f; \
  float r057 = 0.0f; \
  float r058 = 0.0f; \
  float r059 = 0.0f; \
  float r060 = 0.0f; \
  float r061 = 0.0f; \
  float r062 = 0.0f; \
  float r063 = 0.0f; \
  float r064 = 0.0f; \
  float r065 = 0.0f; \
  float r066 = 0.0f; \
  float r067 = 0.0f; \
  float r068 = 0.0f; \
  float r069 = 0.0f; \
  float r070 = 0.0f; \
  float r071 = 0.0f; \
  float r072 = 0.0f; \
  float r073 = 0.0f; \
  float r074 = 0.0f; \
  float r075 = 0.0f; \
  float r076 = 0.0f; \
  float r077 = 0.0f; \
  float r078 = 0.0f; \
  float r079 = 0.0f; \
  float r080 = 0.0f; \
  float r081 = 0.0f; \
  float r082 = 0.0f; \
  float r083 = 0.0f; \
  float r084 = 0.0f; \
  float r085 = 0.0f; \
  float r086 = 0.0f; \
  float r087 = 0.0f; \
  float r088 = 0.0f; \
  float r089 = 0.0f; \
  float r090 = 0.0f; \
  float r091 = 0.0f; \
  float r092 = 0.0f; \
  float r093 = 0.0f; \
  float r094 = 0.0f; \
  float r095 = 0.0f; \
  float r096 = 0.0f; \
  float r097 = 0.0f; \
  float r098 = 0.0f; \
  float r099 = 0.0f; \
  float r100 = 0.0f; \
  float r101 = 0.0f; \
  float r102 = 0.0f; \
  float r103 = 0.0f; \
  float r104 = 0.0f; \
  float r105 = 0.0f; \
  float r106 = 0.0f; \
  float r107 = 0.0f; \
  float r108 = 0.0f; \
  float r109 = 0.0f; \
  float r110 = 0.0f; \
  float r111 = 0.0f; \
  float r112 = 0.0f; \
  float r113 = 0.0f; \
  float r114 = 0.0f; \
  float r115 = 0.0f; \
  float r116 = 0.0f; \
  float r117 = 0.0f; \
  float r118 = 0.0f; \
  float r119 = 0.0f; \
  float r120 = 0.0f; \
  float r121 = 0.0f; \
  float r122 = 0.0f; \
  float r123 = 0.0f; \
  float r124 = 0.0f; \
  float r125 = 0.0f; \
  float r126 = 0.0f; \
  float r127 = 0.0f; \
  float r128 = 0.0f; \
  float r129 = 0.0f; \
  float r130 = 0.0f; \
  float r131 = 0.0f; \
  float r132 = 0.0f; \
  float r133 = 0.0f; \
  float r134 = 0.0f; \
  float r135 = 0.0f; \
  float r136 = 0.0f; \
  float r137 = 0.0f; \
  float r138 = 0.0f; \
  float r139 = 0.0f; \
  float r140 = 0.0f; \
  float r141 = 0.0f; \
  float r142 = 0.0f; \
  float r143 = 0.0f;

#define GDN_LOAD_RF_LAYER_CASE(LAYER) \
  case LAYER: { \
    r000 = init_state[rf_global_offset((LAYER), tid, 0, row_base)]; \
    r001 = init_state[rf_global_offset((LAYER), tid, 1, row_base)]; \
    r002 = init_state[rf_global_offset((LAYER), tid, 2, row_base)]; \
    r003 = init_state[rf_global_offset((LAYER), tid, 3, row_base)]; \
    r004 = init_state[rf_global_offset((LAYER), tid, 4, row_base)]; \
    r005 = init_state[rf_global_offset((LAYER), tid, 5, row_base)]; \
    break; \
  }

#define GDN_LOAD_RF_SWITCH(RUNTIME_LAYER, BODY_DEFAULT) \
  switch (RUNTIME_LAYER) { \
    case 0: { \
      r000 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(0, tid, 0, row_base)] : 0.0f; \
      r001 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(0, tid, 1, row_base)] : 0.0f; \
      r002 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(0, tid, 2, row_base)] : 0.0f; \
      r003 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(0, tid, 3, row_base)] : 0.0f; \
      r004 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(0, tid, 4, row_base)] : 0.0f; \
      r005 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(0, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 1: { \
      r006 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(1, tid, 0, row_base)] : 0.0f; \
      r007 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(1, tid, 1, row_base)] : 0.0f; \
      r008 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(1, tid, 2, row_base)] : 0.0f; \
      r009 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(1, tid, 3, row_base)] : 0.0f; \
      r010 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(1, tid, 4, row_base)] : 0.0f; \
      r011 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(1, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 2: { \
      r012 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(2, tid, 0, row_base)] : 0.0f; \
      r013 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(2, tid, 1, row_base)] : 0.0f; \
      r014 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(2, tid, 2, row_base)] : 0.0f; \
      r015 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(2, tid, 3, row_base)] : 0.0f; \
      r016 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(2, tid, 4, row_base)] : 0.0f; \
      r017 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(2, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 3: { \
      r018 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(3, tid, 0, row_base)] : 0.0f; \
      r019 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(3, tid, 1, row_base)] : 0.0f; \
      r020 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(3, tid, 2, row_base)] : 0.0f; \
      r021 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(3, tid, 3, row_base)] : 0.0f; \
      r022 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(3, tid, 4, row_base)] : 0.0f; \
      r023 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(3, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 4: { \
      r024 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(4, tid, 0, row_base)] : 0.0f; \
      r025 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(4, tid, 1, row_base)] : 0.0f; \
      r026 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(4, tid, 2, row_base)] : 0.0f; \
      r027 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(4, tid, 3, row_base)] : 0.0f; \
      r028 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(4, tid, 4, row_base)] : 0.0f; \
      r029 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(4, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 5: { \
      r030 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(5, tid, 0, row_base)] : 0.0f; \
      r031 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(5, tid, 1, row_base)] : 0.0f; \
      r032 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(5, tid, 2, row_base)] : 0.0f; \
      r033 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(5, tid, 3, row_base)] : 0.0f; \
      r034 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(5, tid, 4, row_base)] : 0.0f; \
      r035 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(5, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 6: { \
      r036 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(6, tid, 0, row_base)] : 0.0f; \
      r037 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(6, tid, 1, row_base)] : 0.0f; \
      r038 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(6, tid, 2, row_base)] : 0.0f; \
      r039 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(6, tid, 3, row_base)] : 0.0f; \
      r040 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(6, tid, 4, row_base)] : 0.0f; \
      r041 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(6, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 7: { \
      r042 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(7, tid, 0, row_base)] : 0.0f; \
      r043 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(7, tid, 1, row_base)] : 0.0f; \
      r044 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(7, tid, 2, row_base)] : 0.0f; \
      r045 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(7, tid, 3, row_base)] : 0.0f; \
      r046 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(7, tid, 4, row_base)] : 0.0f; \
      r047 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(7, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 8: { \
      r048 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(8, tid, 0, row_base)] : 0.0f; \
      r049 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(8, tid, 1, row_base)] : 0.0f; \
      r050 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(8, tid, 2, row_base)] : 0.0f; \
      r051 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(8, tid, 3, row_base)] : 0.0f; \
      r052 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(8, tid, 4, row_base)] : 0.0f; \
      r053 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(8, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 9: { \
      r054 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(9, tid, 0, row_base)] : 0.0f; \
      r055 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(9, tid, 1, row_base)] : 0.0f; \
      r056 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(9, tid, 2, row_base)] : 0.0f; \
      r057 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(9, tid, 3, row_base)] : 0.0f; \
      r058 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(9, tid, 4, row_base)] : 0.0f; \
      r059 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(9, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 10: { \
      r060 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(10, tid, 0, row_base)] : 0.0f; \
      r061 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(10, tid, 1, row_base)] : 0.0f; \
      r062 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(10, tid, 2, row_base)] : 0.0f; \
      r063 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(10, tid, 3, row_base)] : 0.0f; \
      r064 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(10, tid, 4, row_base)] : 0.0f; \
      r065 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(10, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 11: { \
      r066 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(11, tid, 0, row_base)] : 0.0f; \
      r067 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(11, tid, 1, row_base)] : 0.0f; \
      r068 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(11, tid, 2, row_base)] : 0.0f; \
      r069 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(11, tid, 3, row_base)] : 0.0f; \
      r070 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(11, tid, 4, row_base)] : 0.0f; \
      r071 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(11, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 12: { \
      r072 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(12, tid, 0, row_base)] : 0.0f; \
      r073 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(12, tid, 1, row_base)] : 0.0f; \
      r074 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(12, tid, 2, row_base)] : 0.0f; \
      r075 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(12, tid, 3, row_base)] : 0.0f; \
      r076 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(12, tid, 4, row_base)] : 0.0f; \
      r077 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(12, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 13: { \
      r078 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(13, tid, 0, row_base)] : 0.0f; \
      r079 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(13, tid, 1, row_base)] : 0.0f; \
      r080 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(13, tid, 2, row_base)] : 0.0f; \
      r081 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(13, tid, 3, row_base)] : 0.0f; \
      r082 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(13, tid, 4, row_base)] : 0.0f; \
      r083 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(13, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 14: { \
      r084 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(14, tid, 0, row_base)] : 0.0f; \
      r085 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(14, tid, 1, row_base)] : 0.0f; \
      r086 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(14, tid, 2, row_base)] : 0.0f; \
      r087 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(14, tid, 3, row_base)] : 0.0f; \
      r088 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(14, tid, 4, row_base)] : 0.0f; \
      r089 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(14, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 15: { \
      r090 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(15, tid, 0, row_base)] : 0.0f; \
      r091 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(15, tid, 1, row_base)] : 0.0f; \
      r092 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(15, tid, 2, row_base)] : 0.0f; \
      r093 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(15, tid, 3, row_base)] : 0.0f; \
      r094 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(15, tid, 4, row_base)] : 0.0f; \
      r095 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(15, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 16: { \
      r096 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(16, tid, 0, row_base)] : 0.0f; \
      r097 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(16, tid, 1, row_base)] : 0.0f; \
      r098 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(16, tid, 2, row_base)] : 0.0f; \
      r099 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(16, tid, 3, row_base)] : 0.0f; \
      r100 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(16, tid, 4, row_base)] : 0.0f; \
      r101 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(16, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 17: { \
      r102 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(17, tid, 0, row_base)] : 0.0f; \
      r103 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(17, tid, 1, row_base)] : 0.0f; \
      r104 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(17, tid, 2, row_base)] : 0.0f; \
      r105 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(17, tid, 3, row_base)] : 0.0f; \
      r106 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(17, tid, 4, row_base)] : 0.0f; \
      r107 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(17, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 18: { \
      r108 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(18, tid, 0, row_base)] : 0.0f; \
      r109 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(18, tid, 1, row_base)] : 0.0f; \
      r110 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(18, tid, 2, row_base)] : 0.0f; \
      r111 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(18, tid, 3, row_base)] : 0.0f; \
      r112 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(18, tid, 4, row_base)] : 0.0f; \
      r113 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(18, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 19: { \
      r114 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(19, tid, 0, row_base)] : 0.0f; \
      r115 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(19, tid, 1, row_base)] : 0.0f; \
      r116 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(19, tid, 2, row_base)] : 0.0f; \
      r117 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(19, tid, 3, row_base)] : 0.0f; \
      r118 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(19, tid, 4, row_base)] : 0.0f; \
      r119 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(19, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 20: { \
      r120 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(20, tid, 0, row_base)] : 0.0f; \
      r121 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(20, tid, 1, row_base)] : 0.0f; \
      r122 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(20, tid, 2, row_base)] : 0.0f; \
      r123 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(20, tid, 3, row_base)] : 0.0f; \
      r124 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(20, tid, 4, row_base)] : 0.0f; \
      r125 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(20, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 21: { \
      r126 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(21, tid, 0, row_base)] : 0.0f; \
      r127 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(21, tid, 1, row_base)] : 0.0f; \
      r128 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(21, tid, 2, row_base)] : 0.0f; \
      r129 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(21, tid, 3, row_base)] : 0.0f; \
      r130 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(21, tid, 4, row_base)] : 0.0f; \
      r131 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(21, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 22: { \
      r132 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(22, tid, 0, row_base)] : 0.0f; \
      r133 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(22, tid, 1, row_base)] : 0.0f; \
      r134 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(22, tid, 2, row_base)] : 0.0f; \
      r135 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(22, tid, 3, row_base)] : 0.0f; \
      r136 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(22, tid, 4, row_base)] : 0.0f; \
      r137 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(22, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    case 23: { \
      r138 = rf_row_valid(tid, 0, row_base) ? init_state[rf_global_offset(23, tid, 0, row_base)] : 0.0f; \
      r139 = rf_row_valid(tid, 1, row_base) ? init_state[rf_global_offset(23, tid, 1, row_base)] : 0.0f; \
      r140 = rf_row_valid(tid, 2, row_base) ? init_state[rf_global_offset(23, tid, 2, row_base)] : 0.0f; \
      r141 = rf_row_valid(tid, 3, row_base) ? init_state[rf_global_offset(23, tid, 3, row_base)] : 0.0f; \
      r142 = rf_row_valid(tid, 4, row_base) ? init_state[rf_global_offset(23, tid, 4, row_base)] : 0.0f; \
      r143 = rf_row_valid(tid, 5, row_base) ? init_state[rf_global_offset(23, tid, 5, row_base)] : 0.0f; \
      break; \
    } \
    default: { BODY_DEFAULT; break; } \
  }

#define GDN_ADD_RF_SWITCH(RUNTIME_LAYER, BODY_DEFAULT) \
  switch (RUNTIME_LAYER) { \
    case 0: { \
      r000 += delta; \
      r001 += delta; \
      r002 += delta; \
      r003 += delta; \
      r004 += delta; \
      r005 += delta; \
      break; \
    } \
    case 1: { \
      r006 += delta; \
      r007 += delta; \
      r008 += delta; \
      r009 += delta; \
      r010 += delta; \
      r011 += delta; \
      break; \
    } \
    case 2: { \
      r012 += delta; \
      r013 += delta; \
      r014 += delta; \
      r015 += delta; \
      r016 += delta; \
      r017 += delta; \
      break; \
    } \
    case 3: { \
      r018 += delta; \
      r019 += delta; \
      r020 += delta; \
      r021 += delta; \
      r022 += delta; \
      r023 += delta; \
      break; \
    } \
    case 4: { \
      r024 += delta; \
      r025 += delta; \
      r026 += delta; \
      r027 += delta; \
      r028 += delta; \
      r029 += delta; \
      break; \
    } \
    case 5: { \
      r030 += delta; \
      r031 += delta; \
      r032 += delta; \
      r033 += delta; \
      r034 += delta; \
      r035 += delta; \
      break; \
    } \
    case 6: { \
      r036 += delta; \
      r037 += delta; \
      r038 += delta; \
      r039 += delta; \
      r040 += delta; \
      r041 += delta; \
      break; \
    } \
    case 7: { \
      r042 += delta; \
      r043 += delta; \
      r044 += delta; \
      r045 += delta; \
      r046 += delta; \
      r047 += delta; \
      break; \
    } \
    case 8: { \
      r048 += delta; \
      r049 += delta; \
      r050 += delta; \
      r051 += delta; \
      r052 += delta; \
      r053 += delta; \
      break; \
    } \
    case 9: { \
      r054 += delta; \
      r055 += delta; \
      r056 += delta; \
      r057 += delta; \
      r058 += delta; \
      r059 += delta; \
      break; \
    } \
    case 10: { \
      r060 += delta; \
      r061 += delta; \
      r062 += delta; \
      r063 += delta; \
      r064 += delta; \
      r065 += delta; \
      break; \
    } \
    case 11: { \
      r066 += delta; \
      r067 += delta; \
      r068 += delta; \
      r069 += delta; \
      r070 += delta; \
      r071 += delta; \
      break; \
    } \
    case 12: { \
      r072 += delta; \
      r073 += delta; \
      r074 += delta; \
      r075 += delta; \
      r076 += delta; \
      r077 += delta; \
      break; \
    } \
    case 13: { \
      r078 += delta; \
      r079 += delta; \
      r080 += delta; \
      r081 += delta; \
      r082 += delta; \
      r083 += delta; \
      break; \
    } \
    case 14: { \
      r084 += delta; \
      r085 += delta; \
      r086 += delta; \
      r087 += delta; \
      r088 += delta; \
      r089 += delta; \
      break; \
    } \
    case 15: { \
      r090 += delta; \
      r091 += delta; \
      r092 += delta; \
      r093 += delta; \
      r094 += delta; \
      r095 += delta; \
      break; \
    } \
    case 16: { \
      r096 += delta; \
      r097 += delta; \
      r098 += delta; \
      r099 += delta; \
      r100 += delta; \
      r101 += delta; \
      break; \
    } \
    case 17: { \
      r102 += delta; \
      r103 += delta; \
      r104 += delta; \
      r105 += delta; \
      r106 += delta; \
      r107 += delta; \
      break; \
    } \
    case 18: { \
      r108 += delta; \
      r109 += delta; \
      r110 += delta; \
      r111 += delta; \
      r112 += delta; \
      r113 += delta; \
      break; \
    } \
    case 19: { \
      r114 += delta; \
      r115 += delta; \
      r116 += delta; \
      r117 += delta; \
      r118 += delta; \
      r119 += delta; \
      break; \
    } \
    case 20: { \
      r120 += delta; \
      r121 += delta; \
      r122 += delta; \
      r123 += delta; \
      r124 += delta; \
      r125 += delta; \
      break; \
    } \
    case 21: { \
      r126 += delta; \
      r127 += delta; \
      r128 += delta; \
      r129 += delta; \
      r130 += delta; \
      r131 += delta; \
      break; \
    } \
    case 22: { \
      r132 += delta; \
      r133 += delta; \
      r134 += delta; \
      r135 += delta; \
      r136 += delta; \
      r137 += delta; \
      break; \
    } \
    case 23: { \
      r138 += delta; \
      r139 += delta; \
      r140 += delta; \
      r141 += delta; \
      r142 += delta; \
      r143 += delta; \
      break; \
    } \
    default: { BODY_DEFAULT; break; } \
  }

#define GDN_STORE_RF_SWITCH(RUNTIME_LAYER, BODY_DEFAULT) \
  switch (RUNTIME_LAYER) { \
    case 0: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(0, tid, 0, row_base)] = r000; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(0, tid, 1, row_base)] = r001; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(0, tid, 2, row_base)] = r002; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(0, tid, 3, row_base)] = r003; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(0, tid, 4, row_base)] = r004; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(0, tid, 5, row_base)] = r005; } \
      break; \
    } \
    case 1: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(1, tid, 0, row_base)] = r006; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(1, tid, 1, row_base)] = r007; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(1, tid, 2, row_base)] = r008; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(1, tid, 3, row_base)] = r009; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(1, tid, 4, row_base)] = r010; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(1, tid, 5, row_base)] = r011; } \
      break; \
    } \
    case 2: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(2, tid, 0, row_base)] = r012; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(2, tid, 1, row_base)] = r013; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(2, tid, 2, row_base)] = r014; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(2, tid, 3, row_base)] = r015; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(2, tid, 4, row_base)] = r016; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(2, tid, 5, row_base)] = r017; } \
      break; \
    } \
    case 3: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(3, tid, 0, row_base)] = r018; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(3, tid, 1, row_base)] = r019; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(3, tid, 2, row_base)] = r020; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(3, tid, 3, row_base)] = r021; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(3, tid, 4, row_base)] = r022; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(3, tid, 5, row_base)] = r023; } \
      break; \
    } \
    case 4: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(4, tid, 0, row_base)] = r024; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(4, tid, 1, row_base)] = r025; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(4, tid, 2, row_base)] = r026; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(4, tid, 3, row_base)] = r027; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(4, tid, 4, row_base)] = r028; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(4, tid, 5, row_base)] = r029; } \
      break; \
    } \
    case 5: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(5, tid, 0, row_base)] = r030; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(5, tid, 1, row_base)] = r031; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(5, tid, 2, row_base)] = r032; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(5, tid, 3, row_base)] = r033; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(5, tid, 4, row_base)] = r034; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(5, tid, 5, row_base)] = r035; } \
      break; \
    } \
    case 6: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(6, tid, 0, row_base)] = r036; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(6, tid, 1, row_base)] = r037; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(6, tid, 2, row_base)] = r038; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(6, tid, 3, row_base)] = r039; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(6, tid, 4, row_base)] = r040; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(6, tid, 5, row_base)] = r041; } \
      break; \
    } \
    case 7: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(7, tid, 0, row_base)] = r042; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(7, tid, 1, row_base)] = r043; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(7, tid, 2, row_base)] = r044; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(7, tid, 3, row_base)] = r045; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(7, tid, 4, row_base)] = r046; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(7, tid, 5, row_base)] = r047; } \
      break; \
    } \
    case 8: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(8, tid, 0, row_base)] = r048; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(8, tid, 1, row_base)] = r049; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(8, tid, 2, row_base)] = r050; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(8, tid, 3, row_base)] = r051; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(8, tid, 4, row_base)] = r052; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(8, tid, 5, row_base)] = r053; } \
      break; \
    } \
    case 9: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(9, tid, 0, row_base)] = r054; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(9, tid, 1, row_base)] = r055; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(9, tid, 2, row_base)] = r056; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(9, tid, 3, row_base)] = r057; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(9, tid, 4, row_base)] = r058; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(9, tid, 5, row_base)] = r059; } \
      break; \
    } \
    case 10: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(10, tid, 0, row_base)] = r060; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(10, tid, 1, row_base)] = r061; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(10, tid, 2, row_base)] = r062; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(10, tid, 3, row_base)] = r063; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(10, tid, 4, row_base)] = r064; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(10, tid, 5, row_base)] = r065; } \
      break; \
    } \
    case 11: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(11, tid, 0, row_base)] = r066; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(11, tid, 1, row_base)] = r067; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(11, tid, 2, row_base)] = r068; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(11, tid, 3, row_base)] = r069; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(11, tid, 4, row_base)] = r070; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(11, tid, 5, row_base)] = r071; } \
      break; \
    } \
    case 12: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(12, tid, 0, row_base)] = r072; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(12, tid, 1, row_base)] = r073; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(12, tid, 2, row_base)] = r074; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(12, tid, 3, row_base)] = r075; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(12, tid, 4, row_base)] = r076; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(12, tid, 5, row_base)] = r077; } \
      break; \
    } \
    case 13: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(13, tid, 0, row_base)] = r078; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(13, tid, 1, row_base)] = r079; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(13, tid, 2, row_base)] = r080; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(13, tid, 3, row_base)] = r081; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(13, tid, 4, row_base)] = r082; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(13, tid, 5, row_base)] = r083; } \
      break; \
    } \
    case 14: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(14, tid, 0, row_base)] = r084; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(14, tid, 1, row_base)] = r085; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(14, tid, 2, row_base)] = r086; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(14, tid, 3, row_base)] = r087; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(14, tid, 4, row_base)] = r088; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(14, tid, 5, row_base)] = r089; } \
      break; \
    } \
    case 15: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(15, tid, 0, row_base)] = r090; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(15, tid, 1, row_base)] = r091; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(15, tid, 2, row_base)] = r092; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(15, tid, 3, row_base)] = r093; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(15, tid, 4, row_base)] = r094; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(15, tid, 5, row_base)] = r095; } \
      break; \
    } \
    case 16: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(16, tid, 0, row_base)] = r096; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(16, tid, 1, row_base)] = r097; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(16, tid, 2, row_base)] = r098; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(16, tid, 3, row_base)] = r099; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(16, tid, 4, row_base)] = r100; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(16, tid, 5, row_base)] = r101; } \
      break; \
    } \
    case 17: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(17, tid, 0, row_base)] = r102; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(17, tid, 1, row_base)] = r103; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(17, tid, 2, row_base)] = r104; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(17, tid, 3, row_base)] = r105; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(17, tid, 4, row_base)] = r106; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(17, tid, 5, row_base)] = r107; } \
      break; \
    } \
    case 18: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(18, tid, 0, row_base)] = r108; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(18, tid, 1, row_base)] = r109; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(18, tid, 2, row_base)] = r110; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(18, tid, 3, row_base)] = r111; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(18, tid, 4, row_base)] = r112; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(18, tid, 5, row_base)] = r113; } \
      break; \
    } \
    case 19: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(19, tid, 0, row_base)] = r114; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(19, tid, 1, row_base)] = r115; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(19, tid, 2, row_base)] = r116; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(19, tid, 3, row_base)] = r117; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(19, tid, 4, row_base)] = r118; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(19, tid, 5, row_base)] = r119; } \
      break; \
    } \
    case 20: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(20, tid, 0, row_base)] = r120; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(20, tid, 1, row_base)] = r121; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(20, tid, 2, row_base)] = r122; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(20, tid, 3, row_base)] = r123; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(20, tid, 4, row_base)] = r124; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(20, tid, 5, row_base)] = r125; } \
      break; \
    } \
    case 21: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(21, tid, 0, row_base)] = r126; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(21, tid, 1, row_base)] = r127; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(21, tid, 2, row_base)] = r128; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(21, tid, 3, row_base)] = r129; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(21, tid, 4, row_base)] = r130; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(21, tid, 5, row_base)] = r131; } \
      break; \
    } \
    case 22: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(22, tid, 0, row_base)] = r132; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(22, tid, 1, row_base)] = r133; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(22, tid, 2, row_base)] = r134; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(22, tid, 3, row_base)] = r135; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(22, tid, 4, row_base)] = r136; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(22, tid, 5, row_base)] = r137; } \
      break; \
    } \
    case 23: { \
      if (rf_row_valid(tid, 0, row_base)) { final_state[rf_global_offset(23, tid, 0, row_base)] = r138; } \
      if (rf_row_valid(tid, 1, row_base)) { final_state[rf_global_offset(23, tid, 1, row_base)] = r139; } \
      if (rf_row_valid(tid, 2, row_base)) { final_state[rf_global_offset(23, tid, 2, row_base)] = r140; } \
      if (rf_row_valid(tid, 3, row_base)) { final_state[rf_global_offset(23, tid, 3, row_base)] = r141; } \
      if (rf_row_valid(tid, 4, row_base)) { final_state[rf_global_offset(23, tid, 4, row_base)] = r142; } \
      if (rf_row_valid(tid, 5, row_base)) { final_state[rf_global_offset(23, tid, 5, row_base)] = r143; } \
      break; \
    } \
    default: { BODY_DEFAULT; break; } \
  }

#define GDN_STAGE_RF_SWITCH(RUNTIME_LAYER, BODY_DEFAULT) \
  switch (RUNTIME_LAYER) { \
    case 0: { \
      rf_stage[tid + 0 * kThreads] = r000; \
      rf_stage[tid + 1 * kThreads] = r001; \
      rf_stage[tid + 2 * kThreads] = r002; \
      rf_stage[tid + 3 * kThreads] = r003; \
      rf_stage[tid + 4 * kThreads] = r004; \
      rf_stage[tid + 5 * kThreads] = r005; \
      break; \
    } \
    case 1: { \
      rf_stage[tid + 0 * kThreads] = r006; \
      rf_stage[tid + 1 * kThreads] = r007; \
      rf_stage[tid + 2 * kThreads] = r008; \
      rf_stage[tid + 3 * kThreads] = r009; \
      rf_stage[tid + 4 * kThreads] = r010; \
      rf_stage[tid + 5 * kThreads] = r011; \
      break; \
    } \
    case 2: { \
      rf_stage[tid + 0 * kThreads] = r012; \
      rf_stage[tid + 1 * kThreads] = r013; \
      rf_stage[tid + 2 * kThreads] = r014; \
      rf_stage[tid + 3 * kThreads] = r015; \
      rf_stage[tid + 4 * kThreads] = r016; \
      rf_stage[tid + 5 * kThreads] = r017; \
      break; \
    } \
    case 3: { \
      rf_stage[tid + 0 * kThreads] = r018; \
      rf_stage[tid + 1 * kThreads] = r019; \
      rf_stage[tid + 2 * kThreads] = r020; \
      rf_stage[tid + 3 * kThreads] = r021; \
      rf_stage[tid + 4 * kThreads] = r022; \
      rf_stage[tid + 5 * kThreads] = r023; \
      break; \
    } \
    case 4: { \
      rf_stage[tid + 0 * kThreads] = r024; \
      rf_stage[tid + 1 * kThreads] = r025; \
      rf_stage[tid + 2 * kThreads] = r026; \
      rf_stage[tid + 3 * kThreads] = r027; \
      rf_stage[tid + 4 * kThreads] = r028; \
      rf_stage[tid + 5 * kThreads] = r029; \
      break; \
    } \
    case 5: { \
      rf_stage[tid + 0 * kThreads] = r030; \
      rf_stage[tid + 1 * kThreads] = r031; \
      rf_stage[tid + 2 * kThreads] = r032; \
      rf_stage[tid + 3 * kThreads] = r033; \
      rf_stage[tid + 4 * kThreads] = r034; \
      rf_stage[tid + 5 * kThreads] = r035; \
      break; \
    } \
    case 6: { \
      rf_stage[tid + 0 * kThreads] = r036; \
      rf_stage[tid + 1 * kThreads] = r037; \
      rf_stage[tid + 2 * kThreads] = r038; \
      rf_stage[tid + 3 * kThreads] = r039; \
      rf_stage[tid + 4 * kThreads] = r040; \
      rf_stage[tid + 5 * kThreads] = r041; \
      break; \
    } \
    case 7: { \
      rf_stage[tid + 0 * kThreads] = r042; \
      rf_stage[tid + 1 * kThreads] = r043; \
      rf_stage[tid + 2 * kThreads] = r044; \
      rf_stage[tid + 3 * kThreads] = r045; \
      rf_stage[tid + 4 * kThreads] = r046; \
      rf_stage[tid + 5 * kThreads] = r047; \
      break; \
    } \
    case 8: { \
      rf_stage[tid + 0 * kThreads] = r048; \
      rf_stage[tid + 1 * kThreads] = r049; \
      rf_stage[tid + 2 * kThreads] = r050; \
      rf_stage[tid + 3 * kThreads] = r051; \
      rf_stage[tid + 4 * kThreads] = r052; \
      rf_stage[tid + 5 * kThreads] = r053; \
      break; \
    } \
    case 9: { \
      rf_stage[tid + 0 * kThreads] = r054; \
      rf_stage[tid + 1 * kThreads] = r055; \
      rf_stage[tid + 2 * kThreads] = r056; \
      rf_stage[tid + 3 * kThreads] = r057; \
      rf_stage[tid + 4 * kThreads] = r058; \
      rf_stage[tid + 5 * kThreads] = r059; \
      break; \
    } \
    case 10: { \
      rf_stage[tid + 0 * kThreads] = r060; \
      rf_stage[tid + 1 * kThreads] = r061; \
      rf_stage[tid + 2 * kThreads] = r062; \
      rf_stage[tid + 3 * kThreads] = r063; \
      rf_stage[tid + 4 * kThreads] = r064; \
      rf_stage[tid + 5 * kThreads] = r065; \
      break; \
    } \
    case 11: { \
      rf_stage[tid + 0 * kThreads] = r066; \
      rf_stage[tid + 1 * kThreads] = r067; \
      rf_stage[tid + 2 * kThreads] = r068; \
      rf_stage[tid + 3 * kThreads] = r069; \
      rf_stage[tid + 4 * kThreads] = r070; \
      rf_stage[tid + 5 * kThreads] = r071; \
      break; \
    } \
    case 12: { \
      rf_stage[tid + 0 * kThreads] = r072; \
      rf_stage[tid + 1 * kThreads] = r073; \
      rf_stage[tid + 2 * kThreads] = r074; \
      rf_stage[tid + 3 * kThreads] = r075; \
      rf_stage[tid + 4 * kThreads] = r076; \
      rf_stage[tid + 5 * kThreads] = r077; \
      break; \
    } \
    case 13: { \
      rf_stage[tid + 0 * kThreads] = r078; \
      rf_stage[tid + 1 * kThreads] = r079; \
      rf_stage[tid + 2 * kThreads] = r080; \
      rf_stage[tid + 3 * kThreads] = r081; \
      rf_stage[tid + 4 * kThreads] = r082; \
      rf_stage[tid + 5 * kThreads] = r083; \
      break; \
    } \
    case 14: { \
      rf_stage[tid + 0 * kThreads] = r084; \
      rf_stage[tid + 1 * kThreads] = r085; \
      rf_stage[tid + 2 * kThreads] = r086; \
      rf_stage[tid + 3 * kThreads] = r087; \
      rf_stage[tid + 4 * kThreads] = r088; \
      rf_stage[tid + 5 * kThreads] = r089; \
      break; \
    } \
    case 15: { \
      rf_stage[tid + 0 * kThreads] = r090; \
      rf_stage[tid + 1 * kThreads] = r091; \
      rf_stage[tid + 2 * kThreads] = r092; \
      rf_stage[tid + 3 * kThreads] = r093; \
      rf_stage[tid + 4 * kThreads] = r094; \
      rf_stage[tid + 5 * kThreads] = r095; \
      break; \
    } \
    case 16: { \
      rf_stage[tid + 0 * kThreads] = r096; \
      rf_stage[tid + 1 * kThreads] = r097; \
      rf_stage[tid + 2 * kThreads] = r098; \
      rf_stage[tid + 3 * kThreads] = r099; \
      rf_stage[tid + 4 * kThreads] = r100; \
      rf_stage[tid + 5 * kThreads] = r101; \
      break; \
    } \
    case 17: { \
      rf_stage[tid + 0 * kThreads] = r102; \
      rf_stage[tid + 1 * kThreads] = r103; \
      rf_stage[tid + 2 * kThreads] = r104; \
      rf_stage[tid + 3 * kThreads] = r105; \
      rf_stage[tid + 4 * kThreads] = r106; \
      rf_stage[tid + 5 * kThreads] = r107; \
      break; \
    } \
    case 18: { \
      rf_stage[tid + 0 * kThreads] = r108; \
      rf_stage[tid + 1 * kThreads] = r109; \
      rf_stage[tid + 2 * kThreads] = r110; \
      rf_stage[tid + 3 * kThreads] = r111; \
      rf_stage[tid + 4 * kThreads] = r112; \
      rf_stage[tid + 5 * kThreads] = r113; \
      break; \
    } \
    case 19: { \
      rf_stage[tid + 0 * kThreads] = r114; \
      rf_stage[tid + 1 * kThreads] = r115; \
      rf_stage[tid + 2 * kThreads] = r116; \
      rf_stage[tid + 3 * kThreads] = r117; \
      rf_stage[tid + 4 * kThreads] = r118; \
      rf_stage[tid + 5 * kThreads] = r119; \
      break; \
    } \
    case 20: { \
      rf_stage[tid + 0 * kThreads] = r120; \
      rf_stage[tid + 1 * kThreads] = r121; \
      rf_stage[tid + 2 * kThreads] = r122; \
      rf_stage[tid + 3 * kThreads] = r123; \
      rf_stage[tid + 4 * kThreads] = r124; \
      rf_stage[tid + 5 * kThreads] = r125; \
      break; \
    } \
    case 21: { \
      rf_stage[tid + 0 * kThreads] = r126; \
      rf_stage[tid + 1 * kThreads] = r127; \
      rf_stage[tid + 2 * kThreads] = r128; \
      rf_stage[tid + 3 * kThreads] = r129; \
      rf_stage[tid + 4 * kThreads] = r130; \
      rf_stage[tid + 5 * kThreads] = r131; \
      break; \
    } \
    case 22: { \
      rf_stage[tid + 0 * kThreads] = r132; \
      rf_stage[tid + 1 * kThreads] = r133; \
      rf_stage[tid + 2 * kThreads] = r134; \
      rf_stage[tid + 3 * kThreads] = r135; \
      rf_stage[tid + 4 * kThreads] = r136; \
      rf_stage[tid + 5 * kThreads] = r137; \
      break; \
    } \
    case 23: { \
      rf_stage[tid + 0 * kThreads] = r138; \
      rf_stage[tid + 1 * kThreads] = r139; \
      rf_stage[tid + 2 * kThreads] = r140; \
      rf_stage[tid + 3 * kThreads] = r141; \
      rf_stage[tid + 4 * kThreads] = r142; \
      rf_stage[tid + 5 * kThreads] = r143; \
      break; \
    } \
    default: { BODY_DEFAULT; break; } \
  }

#define GDN_UNSTAGE_RF_SWITCH(RUNTIME_LAYER, BODY_DEFAULT) \
  switch (RUNTIME_LAYER) { \
    case 0: { \
      r000 = rf_stage[tid + 0 * kThreads]; \
      r001 = rf_stage[tid + 1 * kThreads]; \
      r002 = rf_stage[tid + 2 * kThreads]; \
      r003 = rf_stage[tid + 3 * kThreads]; \
      r004 = rf_stage[tid + 4 * kThreads]; \
      r005 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 1: { \
      r006 = rf_stage[tid + 0 * kThreads]; \
      r007 = rf_stage[tid + 1 * kThreads]; \
      r008 = rf_stage[tid + 2 * kThreads]; \
      r009 = rf_stage[tid + 3 * kThreads]; \
      r010 = rf_stage[tid + 4 * kThreads]; \
      r011 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 2: { \
      r012 = rf_stage[tid + 0 * kThreads]; \
      r013 = rf_stage[tid + 1 * kThreads]; \
      r014 = rf_stage[tid + 2 * kThreads]; \
      r015 = rf_stage[tid + 3 * kThreads]; \
      r016 = rf_stage[tid + 4 * kThreads]; \
      r017 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 3: { \
      r018 = rf_stage[tid + 0 * kThreads]; \
      r019 = rf_stage[tid + 1 * kThreads]; \
      r020 = rf_stage[tid + 2 * kThreads]; \
      r021 = rf_stage[tid + 3 * kThreads]; \
      r022 = rf_stage[tid + 4 * kThreads]; \
      r023 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 4: { \
      r024 = rf_stage[tid + 0 * kThreads]; \
      r025 = rf_stage[tid + 1 * kThreads]; \
      r026 = rf_stage[tid + 2 * kThreads]; \
      r027 = rf_stage[tid + 3 * kThreads]; \
      r028 = rf_stage[tid + 4 * kThreads]; \
      r029 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 5: { \
      r030 = rf_stage[tid + 0 * kThreads]; \
      r031 = rf_stage[tid + 1 * kThreads]; \
      r032 = rf_stage[tid + 2 * kThreads]; \
      r033 = rf_stage[tid + 3 * kThreads]; \
      r034 = rf_stage[tid + 4 * kThreads]; \
      r035 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 6: { \
      r036 = rf_stage[tid + 0 * kThreads]; \
      r037 = rf_stage[tid + 1 * kThreads]; \
      r038 = rf_stage[tid + 2 * kThreads]; \
      r039 = rf_stage[tid + 3 * kThreads]; \
      r040 = rf_stage[tid + 4 * kThreads]; \
      r041 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 7: { \
      r042 = rf_stage[tid + 0 * kThreads]; \
      r043 = rf_stage[tid + 1 * kThreads]; \
      r044 = rf_stage[tid + 2 * kThreads]; \
      r045 = rf_stage[tid + 3 * kThreads]; \
      r046 = rf_stage[tid + 4 * kThreads]; \
      r047 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 8: { \
      r048 = rf_stage[tid + 0 * kThreads]; \
      r049 = rf_stage[tid + 1 * kThreads]; \
      r050 = rf_stage[tid + 2 * kThreads]; \
      r051 = rf_stage[tid + 3 * kThreads]; \
      r052 = rf_stage[tid + 4 * kThreads]; \
      r053 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 9: { \
      r054 = rf_stage[tid + 0 * kThreads]; \
      r055 = rf_stage[tid + 1 * kThreads]; \
      r056 = rf_stage[tid + 2 * kThreads]; \
      r057 = rf_stage[tid + 3 * kThreads]; \
      r058 = rf_stage[tid + 4 * kThreads]; \
      r059 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 10: { \
      r060 = rf_stage[tid + 0 * kThreads]; \
      r061 = rf_stage[tid + 1 * kThreads]; \
      r062 = rf_stage[tid + 2 * kThreads]; \
      r063 = rf_stage[tid + 3 * kThreads]; \
      r064 = rf_stage[tid + 4 * kThreads]; \
      r065 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 11: { \
      r066 = rf_stage[tid + 0 * kThreads]; \
      r067 = rf_stage[tid + 1 * kThreads]; \
      r068 = rf_stage[tid + 2 * kThreads]; \
      r069 = rf_stage[tid + 3 * kThreads]; \
      r070 = rf_stage[tid + 4 * kThreads]; \
      r071 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 12: { \
      r072 = rf_stage[tid + 0 * kThreads]; \
      r073 = rf_stage[tid + 1 * kThreads]; \
      r074 = rf_stage[tid + 2 * kThreads]; \
      r075 = rf_stage[tid + 3 * kThreads]; \
      r076 = rf_stage[tid + 4 * kThreads]; \
      r077 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 13: { \
      r078 = rf_stage[tid + 0 * kThreads]; \
      r079 = rf_stage[tid + 1 * kThreads]; \
      r080 = rf_stage[tid + 2 * kThreads]; \
      r081 = rf_stage[tid + 3 * kThreads]; \
      r082 = rf_stage[tid + 4 * kThreads]; \
      r083 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 14: { \
      r084 = rf_stage[tid + 0 * kThreads]; \
      r085 = rf_stage[tid + 1 * kThreads]; \
      r086 = rf_stage[tid + 2 * kThreads]; \
      r087 = rf_stage[tid + 3 * kThreads]; \
      r088 = rf_stage[tid + 4 * kThreads]; \
      r089 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 15: { \
      r090 = rf_stage[tid + 0 * kThreads]; \
      r091 = rf_stage[tid + 1 * kThreads]; \
      r092 = rf_stage[tid + 2 * kThreads]; \
      r093 = rf_stage[tid + 3 * kThreads]; \
      r094 = rf_stage[tid + 4 * kThreads]; \
      r095 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 16: { \
      r096 = rf_stage[tid + 0 * kThreads]; \
      r097 = rf_stage[tid + 1 * kThreads]; \
      r098 = rf_stage[tid + 2 * kThreads]; \
      r099 = rf_stage[tid + 3 * kThreads]; \
      r100 = rf_stage[tid + 4 * kThreads]; \
      r101 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 17: { \
      r102 = rf_stage[tid + 0 * kThreads]; \
      r103 = rf_stage[tid + 1 * kThreads]; \
      r104 = rf_stage[tid + 2 * kThreads]; \
      r105 = rf_stage[tid + 3 * kThreads]; \
      r106 = rf_stage[tid + 4 * kThreads]; \
      r107 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 18: { \
      r108 = rf_stage[tid + 0 * kThreads]; \
      r109 = rf_stage[tid + 1 * kThreads]; \
      r110 = rf_stage[tid + 2 * kThreads]; \
      r111 = rf_stage[tid + 3 * kThreads]; \
      r112 = rf_stage[tid + 4 * kThreads]; \
      r113 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 19: { \
      r114 = rf_stage[tid + 0 * kThreads]; \
      r115 = rf_stage[tid + 1 * kThreads]; \
      r116 = rf_stage[tid + 2 * kThreads]; \
      r117 = rf_stage[tid + 3 * kThreads]; \
      r118 = rf_stage[tid + 4 * kThreads]; \
      r119 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 20: { \
      r120 = rf_stage[tid + 0 * kThreads]; \
      r121 = rf_stage[tid + 1 * kThreads]; \
      r122 = rf_stage[tid + 2 * kThreads]; \
      r123 = rf_stage[tid + 3 * kThreads]; \
      r124 = rf_stage[tid + 4 * kThreads]; \
      r125 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 21: { \
      r126 = rf_stage[tid + 0 * kThreads]; \
      r127 = rf_stage[tid + 1 * kThreads]; \
      r128 = rf_stage[tid + 2 * kThreads]; \
      r129 = rf_stage[tid + 3 * kThreads]; \
      r130 = rf_stage[tid + 4 * kThreads]; \
      r131 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 22: { \
      r132 = rf_stage[tid + 0 * kThreads]; \
      r133 = rf_stage[tid + 1 * kThreads]; \
      r134 = rf_stage[tid + 2 * kThreads]; \
      r135 = rf_stage[tid + 3 * kThreads]; \
      r136 = rf_stage[tid + 4 * kThreads]; \
      r137 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    case 23: { \
      r138 = rf_stage[tid + 0 * kThreads]; \
      r139 = rf_stage[tid + 1 * kThreads]; \
      r140 = rf_stage[tid + 2 * kThreads]; \
      r141 = rf_stage[tid + 3 * kThreads]; \
      r142 = rf_stage[tid + 4 * kThreads]; \
      r143 = rf_stage[tid + 5 * kThreads]; \
      break; \
    } \
    default: { BODY_DEFAULT; break; } \
  }

#define GDN_LOAD_RF_BF16_SWITCH(RUNTIME_LAYER, BODY_DEFAULT) \
  switch (RUNTIME_LAYER) { \
    case 0: { \
      r000 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r001 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r002 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r003 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r004 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r005 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 1: { \
      r006 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r007 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r008 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r009 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r010 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r011 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 2: { \
      r012 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r013 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r014 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r015 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r016 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r017 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 3: { \
      r018 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r019 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r020 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r021 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r022 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r023 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 4: { \
      r024 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r025 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r026 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r027 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r028 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r029 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 5: { \
      r030 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r031 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r032 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r033 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r034 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r035 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 6: { \
      r036 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r037 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r038 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r039 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r040 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r041 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 7: { \
      r042 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r043 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r044 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r045 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r046 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r047 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 8: { \
      r048 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r049 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r050 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r051 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r052 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r053 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 9: { \
      r054 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r055 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r056 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r057 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r058 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r059 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 10: { \
      r060 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r061 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r062 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r063 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r064 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r065 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 11: { \
      r066 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r067 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r068 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r069 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r070 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r071 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 12: { \
      r072 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r073 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r074 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r075 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r076 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r077 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 13: { \
      r078 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r079 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r080 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r081 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r082 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r083 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 14: { \
      r084 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r085 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r086 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r087 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r088 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r089 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 15: { \
      r090 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r091 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r092 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r093 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r094 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r095 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 16: { \
      r096 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r097 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r098 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r099 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r100 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r101 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 17: { \
      r102 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r103 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r104 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r105 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r106 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r107 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 18: { \
      r108 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r109 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r110 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r111 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r112 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r113 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 19: { \
      r114 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r115 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r116 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r117 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r118 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r119 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 20: { \
      r120 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r121 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r122 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r123 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r124 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r125 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 21: { \
      r126 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r127 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r128 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r129 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r130 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r131 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 22: { \
      r132 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r133 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r134 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r135 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r136 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r137 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    case 23: { \
      r138 = rf_row_valid(tid, 0, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 0, row_base)]) : 0.0f; \
      r139 = rf_row_valid(tid, 1, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 1, row_base)]) : 0.0f; \
      r140 = rf_row_valid(tid, 2, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 2, row_base)]) : 0.0f; \
      r141 = rf_row_valid(tid, 3, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 3, row_base)]) : 0.0f; \
      r142 = rf_row_valid(tid, 4, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 4, row_base)]) : 0.0f; \
      r143 = rf_row_valid(tid, 5, row_base) ? __bfloat162float(state[rf_layer_offset(tid, 5, row_base)]) : 0.0f; \
      break; \
    } \
    default: { BODY_DEFAULT; break; } \
  }

#define GDN_STORE_RF_BF16_SWITCH(RUNTIME_LAYER, BODY_DEFAULT) \
  switch (RUNTIME_LAYER) { \
    case 0: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r000); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r001); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r002); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r003); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r004); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r005); }; \
      break; \
    } \
    case 1: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r006); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r007); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r008); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r009); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r010); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r011); }; \
      break; \
    } \
    case 2: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r012); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r013); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r014); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r015); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r016); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r017); }; \
      break; \
    } \
    case 3: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r018); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r019); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r020); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r021); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r022); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r023); }; \
      break; \
    } \
    case 4: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r024); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r025); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r026); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r027); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r028); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r029); }; \
      break; \
    } \
    case 5: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r030); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r031); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r032); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r033); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r034); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r035); }; \
      break; \
    } \
    case 6: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r036); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r037); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r038); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r039); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r040); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r041); }; \
      break; \
    } \
    case 7: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r042); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r043); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r044); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r045); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r046); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r047); }; \
      break; \
    } \
    case 8: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r048); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r049); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r050); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r051); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r052); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r053); }; \
      break; \
    } \
    case 9: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r054); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r055); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r056); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r057); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r058); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r059); }; \
      break; \
    } \
    case 10: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r060); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r061); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r062); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r063); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r064); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r065); }; \
      break; \
    } \
    case 11: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r066); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r067); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r068); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r069); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r070); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r071); }; \
      break; \
    } \
    case 12: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r072); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r073); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r074); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r075); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r076); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r077); }; \
      break; \
    } \
    case 13: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r078); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r079); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r080); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r081); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r082); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r083); }; \
      break; \
    } \
    case 14: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r084); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r085); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r086); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r087); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r088); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r089); }; \
      break; \
    } \
    case 15: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r090); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r091); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r092); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r093); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r094); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r095); }; \
      break; \
    } \
    case 16: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r096); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r097); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r098); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r099); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r100); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r101); }; \
      break; \
    } \
    case 17: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r102); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r103); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r104); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r105); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r106); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r107); }; \
      break; \
    } \
    case 18: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r108); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r109); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r110); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r111); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r112); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r113); }; \
      break; \
    } \
    case 19: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r114); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r115); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r116); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r117); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r118); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r119); }; \
      break; \
    } \
    case 20: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r120); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r121); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r122); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r123); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r124); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r125); }; \
      break; \
    } \
    case 21: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r126); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r127); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r128); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r129); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r130); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r131); }; \
      break; \
    } \
    case 22: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r132); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r133); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r134); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r135); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r136); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r137); }; \
      break; \
    } \
    case 23: { \
      if (rf_row_valid(tid, 0, row_base)) { state[rf_layer_offset(tid, 0, row_base)] = __float2bfloat16_rn(r138); }; \
      if (rf_row_valid(tid, 1, row_base)) { state[rf_layer_offset(tid, 1, row_base)] = __float2bfloat16_rn(r139); }; \
      if (rf_row_valid(tid, 2, row_base)) { state[rf_layer_offset(tid, 2, row_base)] = __float2bfloat16_rn(r140); }; \
      if (rf_row_valid(tid, 3, row_base)) { state[rf_layer_offset(tid, 3, row_base)] = __float2bfloat16_rn(r141); }; \
      if (rf_row_valid(tid, 4, row_base)) { state[rf_layer_offset(tid, 4, row_base)] = __float2bfloat16_rn(r142); }; \
      if (rf_row_valid(tid, 5, row_base)) { state[rf_layer_offset(tid, 5, row_base)] = __float2bfloat16_rn(r143); }; \
      break; \
    } \
    default: { BODY_DEFAULT; break; } \
  }

// clang-format on
